language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb

env:
	- TESTDB=nedb
  - TESTDB=mongo

after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose