language: node_js
node_js:
  - '0.12'
services:
  - mongodb
after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
deploy:
  provider: npm
  email: austinwm@gmail.com
  api_key:
    secure: aEX8WNVjrTTHkeFZAMDA8OwER91lZR2cTPDtKVi/+KswPnf0XEey+tSc8AW2Jpd1Iw2u6ixHMbtA8yDDq3LoZcCls/Y/XQ9hahoa5SYCChQnu0TFDZXBG5b0YfLbcgkoOV3GSjhu7gVJn7RLJHNEeCBIhAF6e82dLGFyYzQZMDY=
  on:
    tags: true
    all_branches: true
    repo: amcgee/remjs
notifications:
  slack: welldonetech:yF3HybtHHNfxzf0nKhEyG0mC
sudo: false
